version: '3.8'

services:
  psql:
    container_name: schedule-db
    image: postgres:14.4-alpine
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - psql_vol:/var/lib/postgresql/data

  backend:
    container_name: schedule-backend
    image: schedule-backend
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - backend_logs_vol:/schedule/logs
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    depends_on:
      - psql

  calendar:
    container_name: schedule-cal
    image: schedule-cal
    restart: always
    ports:
      - "8080:3000"
    build:
      context: ../calendar-ui
      dockerfile: Dockerfile

volumes:
  psql_vol:
  backend_logs_vol: