version: '3.8'

services:
  psql:
    container_name: schedule-db
    image: postgres:13.2
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - psql_vol:/var/lib/postgresql/data

  backend:
    container_name: schedule-backend
    image: schedule-backend
    restart: always
    ports:
      - 9000:9000
    environment:
      SCHEDULE_SECRET_KEY: ${SECRET_KEY}
      SCHEDULE_DB_URL: jdbc:postgresql://psql:5432/${DB_NAME}
      SCHEDULE_DB_NAME: ${DB_NAME}
      SCHEDULE_DB_USER: ${USERNAME}
      SCHEDULE_DB_PASSWORD: ${PASSWORD}
    volumes:
      - backend_logs_vol:/schedule/logs
    depends_on:
      - psql

volumes:
  psql_vol:
  backend_logs_vol: