version: '3.8'

services:
  psql:
    container_name: schedule-db
    image: postgres:13.2
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - psql_vol:/var/lib/postgresql/data

  backend:
    container_name: schedule-backend
    image: schedule-backend
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - backend_logs_vol:/schedule/logs
    depends_on:
      - psql

  frontend:
    container_name: schedule-frontend
    image: schedule-frontend
    restart: always
    ports:
      - "8080:80"
      - "4433:443"
    volumes:
      - nginx_cert_vol:/etc/cert
      - nginx_config_vol:/etc/nginx/conf.d

volumes:
  psql_vol:
  backend_logs_vol:
  nginx_cert_vol:
  nginx_config_vol: