version: '3.8'

services:
  psql:
    container_name: schedule-db
    image: postgres:14.4-alpine
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - psql_vol:/var/lib/postgresql/data

  backend:
    container_name: schedule-backend
    image: schedule-backend
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - backend_logs_vol:/schedule/logs
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    depends_on:
      - psql

  frontend:
    container_name: schedule-frontend
    image: schedule-frontend
    restart: always
    ports:
      - "8080:80"
      - "4433:443"
    build:
      context: ../schedule-ui
      dockerfile: Dockerfile
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
        mode: 0440
    secrets:
      - source: server_cert_pem
        target: /etc/cert/cert.pem
        mode: 0440
      - source: server_cert_key
        target: /etc/cert/cert.key
        mode: 0440

volumes:
  psql_vol:
  backend_logs_vol: